session_name: tmuxp
windows:
- focus: 'true'
  layout: 527d,167x54,0,0[167x31,0,0,21,167x22,0,32{77x22,0,32,22,89x22,78,32,23}]
  options:
    main-pane-height: 35
  panes:
  - nvim
  - focus: 'true'
    shell_command: Python
  - python3.9
  start_directory: /Users/marc/DODOBIRD/DODO_CODE/data-validation
  window_name: tmuxp
