session_name: demo_dev 
start_directory: ~/
# shell_command_before: 
windows:
- focus: 'true'
  layout: 2878,156x67,0,0{56x67,0,0[56x33,0,0,1,56x33,0,34,3],99x67,57,0,2}
  options:
    automatic-rename: 'off'
  panes:
  - ranger 
  - git status 
  - focus: 'true'
    shell_command: nvim "-c '0"
  window_name: dev
